import type { Theater, Artist, Show, ShowFunction, Order } from "@/types/admin"

export const mockTheaters: Theater[] = [
  {
    id: "1",
    name: "Teatro Principal",
    address: "Av. Corrientes 1530",
    city: "Buenos Aires",
    mapUrl: "https://maps.app.goo.gl/1in7p7AxnFxNb9o3A",
    createdAt: new Date("2024-01-15"),
  },
  {
    id: "2",
    name: "Teatro Colón",
    address: "Cerrito 628",
    city: "Buenos Aires",
    mapUrl: "https://maps.app.goo.gl/1in7p7AxnFxNb9o3A",
    createdAt: new Date("2024-02-20"),
  },
  {
    id: "3",
    name: "Teatro Gran Rex",
    address: "Av. Corrientes 857",
    city: "Buenos Aires",
    mapUrl: "https://maps.app.goo.gl/1in7p7AxnFxNb9o3A",
    createdAt: new Date("2024-03-10"),
  },
]

export const mockArtists: Artist[] = [
  {
    id: "1",
    name: "Franky Rizardo",
    bio: "DJ y productor internacional",
    image: "/franky-rizardo.jpg",
    socialMedia: {
      instagram: "@frankyrizardo",
      facebook: "frankyrizardoofficial",
      twitter: "@frankyrizardo",
    },
    createdAt: new Date("2024-01-10"),
  },
  {
    id: "2",
    name: "Smith",
    bio: "Artista urbano reconocido",
    image: "/smith-artist.jpg",
    socialMedia: {
      instagram: "@smithofficial",
      facebook: "smithmusic",
    },
    createdAt: new Date("2024-02-15"),
  },
  {
    id: "3",
    name: "Hozho",
    bio: "Productor de música electrónica",
    image: "/hozho-dj.jpg",
    socialMedia: {
      instagram: "@hozhoofficial",
      twitter: "@hozho",
    },
    createdAt: new Date("2024-03-05"),
  },
]

export const mockShows: Show[] = [
  {
    id: "1",
    title: "Franky Rizardo en Rosario",
    description: "Una noche única con el DJ internacional Franky Rizardo en Blue Open Air",
    duration: 180,
    genre: "Música Electrónica",
    mainImage: "/placeholder-1xbhm.png",
    gallery: ["/dj-stage-1.jpg", "/dj-stage-2.jpg", "/dj-crowd.jpg"],
    theaterId: "1",
    artistIds: ["1"],
    createdAt: new Date("2024-11-20"),
  },
  {
    id: "2",
    title: "Smith Live",
    description: "Concierto especial de Smith presentando sus últimos éxitos",
    duration: 120,
    genre: "Urban/Pop",
    mainImage: "/smith-concert.jpg",
    gallery: ["/urban-concert-1.jpg", "/urban-concert-2.jpg"],
    theaterId: "2",
    artistIds: ["2"],
    createdAt: new Date("2024-11-25"),
  },
  {
    id: "3",
    title: "Hozho Night",
    description: "Noche de música electrónica con Hozho",
    duration: 240,
    genre: "Techno/House",
    mainImage: "/hozho-event.jpg",
    gallery: [],
    theaterId: "3",
    artistIds: ["3"],
    createdAt: new Date("2024-12-01"),
  },
]

export const mockFunctions: ShowFunction[] = [
  {
    id: "1",
    showId: "1",
    theaterId: "1",
    date: new Date("2025-01-09"),
    time: "21:00",
    totalSeats: 500,
    availableSeats: 150,
    price: 5000,
    has2x1Promo: true,
    status: "active",
    createdAt: new Date("2024-11-20"),
  },
  {
    id: "2",
    showId: "2",
    theaterId: "2",
    date: new Date("2024-12-28"),
    time: "20:00",
    totalSeats: 800,
    availableSeats: 0,
    price: 7500,
    has2x1Promo: false,
    status: "sold-out",
    createdAt: new Date("2024-11-25"),
  },
  {
    id: "3",
    showId: "3",
    theaterId: "3",
    date: new Date("2024-12-31"),
    time: "22:00",
    totalSeats: 1200,
    availableSeats: 300,
    price: 10000,
    has2x1Promo: true,
    status: "active",
    createdAt: new Date("2024-12-01"),
  },
]

export const mockOrders: Order[] = [
  {
    id: "ORD001",
    functionId: "1",
    customerName: "Juan Pérez",
    customerEmail: "juan@email.com",
    customerPhone: "+54 9 11 1234-5678",
    ticketQuantity: 2,
    totalAmount: 10000,
    discount: 5000,
    finalAmount: 5000,
    status: "confirmed",
    paymentMethod: "Tarjeta de Crédito",
    createdAt: new Date("2024-12-15"),
    tickets: [
      {
        id: "TKT001",
        orderId: "ORD001",
        functionId: "1",
        qrCode: "QR-TKT001-FRANKY",
        scanned: true,
        scannedAt: new Date("2025-01-09T21:15:00"),
        seatNumber: "A12",
      },
      {
        id: "TKT002",
        orderId: "ORD001",
        functionId: "1",
        qrCode: "QR-TKT002-FRANKY",
        scanned: false,
        seatNumber: "A13",
      },
    ],
  },
  {
    id: "ORD002",
    functionId: "3",
    customerName: "María González",
    customerEmail: "maria@email.com",
    customerPhone: "+54 9 11 9876-5432",
    ticketQuantity: 4,
    totalAmount: 40000,
    discount: 20000,
    finalAmount: 20000,
    status: "confirmed",
    paymentMethod: "Mercado Pago",
    createdAt: new Date("2024-12-18"),
    tickets: [
      {
        id: "TKT003",
        orderId: "ORD002",
        functionId: "3",
        qrCode: "QR-TKT003-HOZHO",
        scanned: false,
        seatNumber: "B5",
      },
      {
        id: "TKT004",
        orderId: "ORD002",
        functionId: "3",
        qrCode: "QR-TKT004-HOZHO",
        scanned: false,
        seatNumber: "B6",
      },
      {
        id: "TKT005",
        orderId: "ORD002",
        functionId: "3",
        qrCode: "QR-TKT005-HOZHO",
        scanned: false,
        seatNumber: "B7",
      },
      {
        id: "TKT006",
        orderId: "ORD002",
        functionId: "3",
        qrCode: "QR-TKT006-HOZHO",
        scanned: false,
        seatNumber: "B8",
      },
    ],
  },
]
