import type { Event } from "@/types/event"

export const featuredEvents: Event[] = [
  {
    id: "1",
    title: "HAMLET",
    subtitle: "Teatro Nacional",
    date: "2025-01-15",
    time: "20:00",
    venue: "Teatro Gran Rex",
    location: "Buenos Aires",
    price: 15000,
    image: "/hamlet-theater-stage-dramatic-lighting.jpg",
    gallery: [
      "/hamlet-theater-stage-dramatic-lighting.jpg",
      "/hamlet-theater-stage-dramatic-lighting.jpg",
      "/hamlet-theater-stage-dramatic-lighting.jpg",
    ],
    featured: true,
    has2x1Promo: true,
    category: "teatro",
    description: "La obra maestra de Shakespeare llega al Gran Rex con un elenco espectacular.",
  },
  {
    id: "2",
    title: "LA CASA DE BERNARDA ALBA",
    subtitle: "Clásico de Lorca",
    date: "2025-01-20",
    time: "21:00",
    venue: "Teatro Colón",
    location: "Buenos Aires",
    price: 18000,
    image: "/spanish-theater-dramatic-stage.jpg",
    gallery: ["/spanish-theater-dramatic-stage.jpg", "/theater-black-dress-performers.jpg"],
    featured: true,
    has2x1Promo: true,
    category: "teatro",
    description: "Una interpretación moderna del clásico de Federico García Lorca.",
  },
  {
    id: "3",
    title: "EL PRINCIPITO",
    subtitle: "Musical Familiar",
    date: "2025-01-25",
    time: "17:00",
    venue: "Teatro Metropolitan",
    location: "Buenos Aires",
    price: 12000,
    image: "/little-prince-musical-theater-stars.jpg",
    gallery: ["/little-prince-musical-theater-stars.jpg", "/family-musical-colorful-stage.jpg"],
    featured: true,
    has2x1Promo: false,
    category: "teatro",
    description: "El musical para toda la familia basado en el clásico de Saint-Exupéry.",
  },
]

export const upcomingEvents: Event[] = [
  {
    id: "4",
    title: "ESPERANDO A GODOT",
    subtitle: "Samuel Beckett",
    date: "2025-02-01",
    time: "20:30",
    venue: "Teatro San Martín",
    location: "Buenos Aires",
    price: 14000,
    image: "/waiting-for-godot-minimalist-stage.jpg",
    has2x1Promo: true,
    category: "teatro",
    description: "La obra existencialista más importante del siglo XX.",
  },
  {
    id: "5",
    title: "LA NONA",
    subtitle: "Roberto Cossa",
    date: "2025-02-05",
    time: "21:00",
    venue: "Teatro Presidente Alvear",
    location: "Buenos Aires",
    price: 13000,
    image: "/argentine-theater-comedy-family.jpg",
    has2x1Promo: true,
    category: "teatro",
    description: "Comedia dramática argentina sobre una familia y su peculiar abuela.",
  },
  {
    id: "6",
    title: "CHICAGO",
    subtitle: "El Musical",
    date: "2025-02-10",
    time: "20:00",
    venue: "Teatro Lola Membrives",
    location: "Buenos Aires",
    price: 20000,
    image: "/chicago-musical-jazz-dancers.jpg",
    has2x1Promo: false,
    category: "musica",
    description: "El icónico musical de Broadway llega a Buenos Aires.",
  },
  {
    id: "7",
    title: "ROMEO Y JULIETA",
    subtitle: "Ballet Clásico",
    date: "2025-02-15",
    time: "19:00",
    venue: "Teatro Colón",
    location: "Buenos Aires",
    price: 16000,
    image: "/ballet-romeo-juliet-dancers.jpg",
    has2x1Promo: true,
    category: "danza",
    description: "Ballet clásico con música de Prokofiev.",
  },
  {
    id: "8",
    title: "STAND UP NACIONAL",
    subtitle: "Los mejores comediantes",
    date: "2025-02-20",
    time: "21:30",
    venue: "Teatro Vorterix",
    location: "Buenos Aires",
    price: 11000,
    image: "/stand-up-comedy-microphone-spotlight.jpg",
    has2x1Promo: false,
    category: "comedia",
    description: "Una noche llena de risas con los mejores comediantes argentinos.",
  },
]
